name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: lint
        run: npm run lint
      - name: test
        run: |
          npm run test:cov
          npm run test:e2e
      - name: build
        run: npm run build
